action_cable
snblack/think pull request #10
Opened 2020-10-19 22:44 UTC by snblack

2020-10-23 09:33 UTC, vkurennov requested changes

2020-10-23 09:33 UTC, vkurennov commented on app/channels/comment_channel.rb
> +    stream_from "question_#{question.id}"
зачем загружать вопрос из базы, если ты используешь только его id, который и так у тебя приходит в `data['question_id']`?

2020-10-23 09:33 UTC, vkurennov commented on app/channels/comment_channel.rb
> +  def parent(data)
не вижу использования этого метода, тогда зачем он нужен?

2020-10-23 09:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      ApplicationController.render(
а вот так делать нельзя, точнее можно, но это не даст верного результата. тут же отрабатывает серверная часть, соответсвенно, current_user здесь - это тот, кто сделал запрос. Про других клиентов сервер ничего не знает, а допустим их еще 1000 подписано на канал. И в итоге, всем 1000 подписчикам пришлем вьюху, такую, какую видит автор (со всякими ссылками на редактирование ,удаление и т.п.), а они  заведом не-авторы.

Поэтому тут должно быть более гибкое решение:

 - Автору отпрапвляем ответ, как до этого, через js-ответ
 - Всем остальным отправляем через AC данные ответа в json
 - На клиенте по user_id определяем, что текущий юзер не является автором (тут как раз понадобится через gon сохранять current_user.id при заходе на любую страницу, чтобы мы могли текущего юзера определить на клиенте), сравнивая user_id, сохраненный через gon и тот, что пришел в данных ответа
 - Если это не автор (т.к. автору ответ уже отправлен, то снова ему рендерить ничего надо), то на клиенте рендерим шаблон ответа, причем упрощенный, без ссылок на удаление, редактирование и т.п. (а как следствие - без лишних проверок)

2020-10-23 09:33 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  def gon_user
ага, вот ты уже сохраняешь user_id, хорошо. только сделай метод приватным, т.к. это не экшн.

2020-10-23 09:33 UTC, vkurennov commented on app/controllers/comments_controller.rb
> +      gon.question_id = question.id
а тебе точно нужны эти данные через gon? ведь внутри самого комментария приходит и commetable_type и commentable_id (при отправке через json), можно их получить на клиенте

2020-10-23 09:33 UTC, vkurennov commented on app/controllers/concerns/commented.rb
> +module Commented
этот консерн не используется, удали его

2020-10-23 09:33 UTC, vkurennov commented on app/javascript/channels/comment_channel.js
> +      $(".answer-comments").find(".comments").append("<p>" + data.body + "</p>")
но ведь ответов на странице может быть много, как ты определяешь ,к какому именно ответу этот комментарий?

2020-10-23 09:33 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  .answer-comments
комментарии должны к каждому ответу отдельно идти, а не общим списком.

2020-10-23 09:33 UTC, vkurennov commented on app/views/questions/show.html.slim
> += '=======Comment======='
попробуй использовать html-комментарии, кажется, они тут как раз и нужны, вместо вывода контента

2020-10-23 09:33 UTC, vkurennov commented on config/routes.rb
> +      concerns :commentable
можно сразу несколько консернов указать:

`concerns: [:commentable,  :votable]`

2020-10-23 09:33 UTC, vkurennov commented on spec/features/answer/create_answer_spec.rb
> +        Capybara.using_session('guest') do
и вот тут добавь, что он не видит ссылок на редактирование ответа, например

2020-10-23 15:38 UTC, snblack commented on app/channels/comment_channel.rb
> +    stream_from "question_#{question.id}"
Done

2020-10-23 15:39 UTC, snblack commented on app/channels/comment_channel.rb
> +  def parent(data)
Done. Использовал в первой версии решения моего.

2020-10-23 15:57 UTC, snblack commented on app/controllers/application_controller.rb
> +  def gon_user
done

2020-10-23 16:01 UTC, snblack commented on app/controllers/comments_controller.rb
> +      gon.question_id = question.id
done

2020-10-23 16:01 UTC, snblack commented on app/controllers/concerns/commented.rb
> +module Commented
done

2020-10-23 16:03 UTC, snblack commented on config/routes.rb
> +      concerns :commentable
Done

2020-10-23 16:10 UTC, snblack commented on spec/features/answer/create_answer_spec.rb
> +        Capybara.using_session('guest') do
done

2020-10-24 17:32 UTC, snblack commented on app/controllers/answers_controller.rb
> +      ApplicationController.render(
Done

2020-10-24 18:21 UTC, snblack commented on app/javascript/channels/comment_channel.js
> +      $(".answer-comments").find(".comments").append("<p>" + data.body + "</p>")
Done

2020-10-24 18:21 UTC, snblack commented on app/views/questions/show.html.slim
> += '=======Comment======='
done

2020-10-24 18:21 UTC, snblack commented on app/views/answers/_answer.html.slim
> +  .answer-comments
done

2020-10-25 09:53 UTC, vkurennov approved these changes

2020-10-27 15:54 UTC, merged