api_for_questions_and_answers
snblack/think pull request #13
Opened 2020-11-08 10:26 UTC by snblack

2020-11-09 08:08 UTC, vkurennov requested changes

2020-11-09 08:08 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +      render json: @answer.errors.full_messages
тут хорошо бы статус передавать, отличный от 200 ок, лучше всего 422 unprocessible entity, статусы особо важны в апи, ведь именно по ним клиент, использующий апи может "судить" об успешности запроса

2020-11-09 08:08 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +    if current_resource_owner.author_of?(@answer)
это проверяется авторизацией через cancancan, а не вручную.

2020-11-09 08:08 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +      @answer.update(answer_params)
здесь тоже могут быть ошибки валидации и их надо возвращать

2020-11-09 08:08 UTC, vkurennov commented on app/controllers/api/v1/answers_controller.rb
> +    if current_resource_owner.author_of?(@answer)
опять же ,у нас теперь авторизация через cancancan

2020-11-09 08:08 UTC, vkurennov commented on app/controllers/api/v1/profiles_controller.rb
> +  def all_without_me
тут хватит стандартного index, ни к чему кастомный экшн делать

2020-11-09 08:08 UTC, vkurennov commented on app/controllers/api/v1/questions_controller.rb
> +class Api::V1::QuestionsController < Api::V1::BaseController
те же замечания, что и к контроллеру ответов

2020-11-09 17:08 UTC, snblack commented on app/controllers/api/v1/answers_controller.rb
> +      render json: @answer.errors.full_messages
done

2020-11-09 17:11 UTC, snblack commented on app/controllers/api/v1/answers_controller.rb
> +    if current_resource_owner.author_of?(@answer)
done

2020-11-09 17:12 UTC, snblack commented on app/controllers/api/v1/answers_controller.rb
> +      @answer.update(answer_params)
done

2020-11-09 17:22 UTC, snblack commented on app/controllers/api/v1/profiles_controller.rb
> +  def all_without_me
Done

2020-11-10 08:21 UTC, vkurennov approved these changes

2020-11-12 14:44 UTC, merged