send_new_answer_to_followers
snblack/think pull request #14
Opened 2020-11-15 09:49 UTC by snblack

2020-11-16 08:16 UTC, vkurennov requested changes

2020-11-16 08:16 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def subscribe
Не стоит слишком сильно расширять контроллер кастомными экшенами. Надо посмотреть на это под другим углом:  это действия не с вопросом, а с подпиской (создание и ее удаление). В таком случае гораздо лучше будет вынести это в отдельный ресурс (контроллер)  и в нем сделать экшены create/destroy

2020-11-16 08:16 UTC, vkurennov commented on app/mailers/daily_digest_mailer.rb
> +    @questions_per_day = Question.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
этот запрос хорошо бы в скоуп вынести

2020-11-16 08:16 UTC, vkurennov commented on app/models/ability.rb
> +    can [:subscribe, :unsubscribe], [Question]
для unsubscirbe другое правило: удалить подписку может только тот, кто ее создал

2020-11-16 08:16 UTC, vkurennov commented on app/models/question.rb
> +  has_and_belongs_to_many :followers, class_name: "User"
лучше использовать ассоциацию `has_many through` + промежуточная модель (как раз ее можно назвать Subscription)

2020-11-16 16:16 UTC, snblack commented on app/controllers/questions_controller.rb
> +  def subscribe
done

2020-11-16 21:55 UTC, snblack commented on app/controllers/questions_controller.rb
> +  def subscribe
done

2020-11-16 21:55 UTC, snblack commented on app/models/ability.rb
> +    can [:subscribe, :unsubscribe], [Question]
done

2020-11-16 21:55 UTC, snblack commented on app/models/question.rb
> +  has_and_belongs_to_many :followers, class_name: "User"
done

2020-11-16 22:00 UTC, snblack commented on app/mailers/daily_digest_mailer.rb
> +    @questions_per_day = Question.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
done

2020-11-17 11:57 UTC, vkurennov requested changes

2020-11-17 11:57 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def subscribe
что-то я не понял, что тут "done"? нужно сделать новый контроллер Subscriptions, в нем экшены create и destroy, а эти экшены убрать из QuestionsController. У тебя в итоге тот же самый код, а замечание помечено как решеное, но это не так.

2020-11-17 11:57 UTC, vkurennov commented on app/mailers/daily_digest_mailer.rb
> +    @questions_per_day = Question.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
то же самое: замечание-то не исправлено

2020-11-17 11:57 UTC, vkurennov commented on app/models/ability.rb
> +    can [:subscribe, :unsubscribe], [Question]
и здесь не исправлено

2020-11-17 11:57 UTC, vkurennov commented on app/models/question.rb
> +  has_and_belongs_to_many :followers, class_name: "User"
не исправлено

2020-11-17 12:09 UTC, vkurennov requested changes

2020-11-17 12:09 UTC, vkurennov commented on app/controllers/subscriptions_controller.rb
> +    @subscription = Subscription.find_by(user_id: current_user.id, question_id: @question.id)
тут авторизация не сработает, точнее сработает неверно. потому что сначала в контроллере будет вызвана авторизация, а только потом ты загрузишь объект `subscription`. Надо либо вынести загрузку объекта в `before_action` и повестить его перед `authorize_resource`, либо в самом экшене вызывать нужный `authorize!` после загрузки объекта (правда, тогда теряется смысл в вызове `authorize_resource` в начале контроллер и лучше тогда и в create вызывать `authorize!`)

2020-11-17 12:09 UTC, vkurennov commented on app/models/ability.rb
> +    can [:create], [Subscription]
зачем тут и ниже (и выше) массивы, если везде по одному значению? массивом задается в правилах несколько значений, если значение одно, то просто указываешь его без массива

2020-11-17 12:09 UTC, vkurennov commented on spec/controllers/subscribes_controller_spec.rb
> +RSpec.describe SubscribesController, type: :controller do
где тесты на этот контроллер?

2020-11-17 12:13 UTC, snblack commented on app/controllers/subscriptions_controller.rb
> +    @subscription = Subscription.find_by(user_id: current_user.id, question_id: @question.id)
done

2020-11-17 12:15 UTC, snblack commented on app/models/ability.rb
> +    can [:create], [Subscription]
done

2020-11-17 13:05 UTC, snblack commented on spec/controllers/subscribes_controller_spec.rb
> +RSpec.describe SubscribesController, type: :controller do
done

2020-11-17 15:07 UTC, merged