Lesson 16 search
snblack/think pull request #15
Opened 2020-11-22 16:11 UTC by snblack

2020-11-23 08:21 UTC, vkurennov requested changes

2020-11-23 08:21 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +  def issue(query, where)
такое лучше выносить в сервис, а не в контроллере делать

2020-11-23 08:21 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    case where
тут бы еще else добавить, чтобы учесть ситуацию, когда придет что-то незапланированное

2020-11-23 08:21 UTC, vkurennov commented on app/views/questions/index.html.slim
> +  = form_with url: "/search", method: :get, local: true do |form|
лучше не url указывать, а url-хелпер, который предоставляется роутингом

2020-11-23 08:21 UTC, vkurennov commented on pg_upgrade_internal.log
> +Running in verbose mode
это и все дальнейшие логи удали из репозитория и добавь в .gitignore

2020-11-23 08:21 UTC, vkurennov commented on spec/features/search/search_spec.rb
> +feature 'user can search question with parameters' do
что-то я не понимаю, как это может работать, если у тебя нет настроек тестов в ThinkingSphinx. Эти тесты вообще проходят? Покажи скрин проходящих тестов, плз.

2020-11-23 08:21 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +class SearchesController < ApplicationController
где тесты этого контроллера?

2020-11-23 10:31 UTC, vkurennov commented on spec/features/search/search_spec.rb
> +    visit root_path
вот это явно можно вынести в background и не дублировать в каждом тесте

2020-11-23 19:11 UTC, snblack commented on app/controllers/searches_controller.rb
> +  def issue(query, where)
done

2020-11-23 19:23 UTC, snblack commented on app/controllers/searches_controller.rb
> +    case where
done

2020-11-23 19:31 UTC, snblack commented on app/views/questions/index.html.slim
> +  = form_with url: "/search", method: :get, local: true do |form|
done

2020-11-23 19:32 UTC, snblack commented on pg_upgrade_internal.log
> +Running in verbose mode
done

2020-11-23 19:32 UTC, snblack commented on spec/features/search/search_spec.rb
> +feature 'user can search question with parameters' do
Done

2020-11-23 19:34 UTC, snblack commented on spec/features/search/search_spec.rb
> +    visit root_path
Done

2020-11-23 20:05 UTC, snblack commented on app/controllers/searches_controller.rb
> +class SearchesController < ApplicationController
done

2020-11-24 11:00 UTC, vkurennov approved these changes

2020-11-25 19:22 UTC, merged