rspec_for_models
snblack/think pull request #2
Opened 2020-08-18 20:25 UTC by snblack

2020-08-19 08:42 UTC, vkurennov requested changes

2020-08-19 08:42 UTC, vkurennov commented on app/models/question.rb
> +  has_many :answers
тут нужна опция, при которой удаление вопроса удалит также и связанные ответы. и не забудь эту опцию протестировать, shoulda-mathcers это умеет.

2020-08-19 08:42 UTC, vkurennov commented on app/models/test.rb
> +class Test < ApplicationRecord
где в задании хоть слово про модель тестов? Здесь другое приложение, не тестирование, а аналог stackoverflow, пользователь может задать вопрос, другие на него отвечают. Тут не предполагается какого-либо тестирования. Так что эту модель и все что с ней связано надо удалить

2020-08-19 08:42 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  it { should validate_presence_of :body }
как в моделях, сначала принято писать ассоциации, потом валидации, так и  в тестах принят тот же порядок

2020-08-19 13:34 UTC, snblack commented on app/models/question.rb
> +  has_many :answers
+

2020-08-19 13:48 UTC, snblack commented on app/models/test.rb
> +class Test < ApplicationRecord
+

2020-08-19 13:48 UTC, snblack commented on spec/models/answer_spec.rb
> +  it { should validate_presence_of :body }
+

2020-08-20 09:21 UTC, vkurennov approved these changes

2020-08-20 15:18 UTC, merged