Lesson 5 accept tests
snblack/think pull request #4
Opened 2020-08-28 12:47 UTC by snblack

2020-08-30 05:00 UTC, vkurennov commented on spec/features/question/browse_spec.rb
> +    expect(page).to have_content question.answers[0].body
опять же, проверить надо список, т.е. несколько ответов и они должны быть разными

2020-08-30 05:00 UTC, vkurennov commented on spec/features/question/create_answer_spec.rb
> +    user = create(:user)
используй given

2020-08-30 05:00 UTC, vkurennov commented on spec/features/question/create_answer_spec.rb
> +    question = user.questions.create(title: 'MyTitle', body: 'MyBody')
используй фабрики

2020-08-30 05:01 UTC, vkurennov commented on spec/features/question/create_answer_spec.rb
> +feature 'user can create answer for question', %q{
пиши описание на английском, пусть корявом (используй гугл переводчик, например). русский текст в коде смотрится очень непрофессионально

2020-08-30 05:01 UTC, vkurennov commented on spec/features/question/create_answer_spec.rb
> +feature 'user can create answer for question', %q{
нужен еще сценарий - проверить, что выводятся ошибки валидации

2020-08-30 05:01 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    # Действия
не нужно так много действий выносить в background

2020-08-30 05:02 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    fill_in 'Email', with: user.email
мы для этого хелпер писали в скринкасте, это хороший прием, используй его

2020-08-30 05:02 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    click_on 'Ask question'
вот это лишнее, можно создать нужые данные через фабрики, если их создание не суть самого теста (а здесь тесты на удаление, не на создание)

2020-08-30 05:03 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    # Действия
дублирование, используй хелпер

2020-08-30 05:03 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    click_on 'Delete question'
зачем вообще показывать ссылку на удаление тому, у кого нет прав на это действие? не показывай ссылку и в тестах и проверяй, что ссылка не видна.

2020-08-30 05:04 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +feature 'User can delete question' do
тут нужен еще сценарий для незалогиненного юзера

2020-08-30 05:04 UTC, vkurennov commented on spec/support/feature_helpers.rb
> +  def sign_in(user)
вот у тебя хелпер для логина, используй его, а не дублируй код

2020-09-01 14:26 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params['question_id'])
+

2020-09-01 18:13 UTC, snblack commented on app/controllers/answers_controller.rb
> +      render :new
+

2020-09-02 17:08 UTC, snblack commented on app/controllers/answers_controller.rb
> +  def new
+

2020-09-02 17:23 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @answer.user_id = current_user.id
+

2020-09-02 18:55 UTC, snblack commented on app/views/questions/show.html.slim
> += link_to 'to answer', new_question_answer_path(question)
+

2020-09-02 18:59 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +    it 'renders edit view' do
+

2020-09-04 13:36 UTC, vkurennov requested changes

2020-09-04 13:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def new
ну так если new не нужен, зачем же ты его оставил? надо удалить экшн

2020-09-04 13:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@answer.question), notice: 'Question can not empty!'
нельзя делать редирект, если объект невалидный, надо рендерить страницу, где была форма и выводить ошибки валидации через модель, т.к. их может быть не одна.

2020-09-04 13:36 UTC, vkurennov commented on app/views/questions/index.html.slim
> +      td= "#{question.title} #{question.body}"
наверное, стоит  только заголовок вопроса выводить, тело-то может быть длинным

2020-09-04 13:36 UTC, vkurennov commented on app/views/questions/show.html.slim
> +-begin
что это? обработки исключений в видах быть не должно ни в коем случае!

2020-09-04 13:36 UTC, vkurennov commented on app/views/questions/show.html.slim
> +                question_path,
нужно обязательно указывать объект, т.е. писать `question_path(question)` или просто `question`, иначе поведение системы не документировано и толком неясно какой объект рельсы здесь подставят (сам не понимаю, почему не сделано так, что такой хелпер без объекта ошибку не выкидывает)

2020-09-04 13:36 UTC, vkurennov commented on app/views/questions/show.html.slim
> += form_with model: [@question, @answer], local: true do |f|
здесь нужен вывод ошибок валидации через паршл ошибок

2020-09-04 13:36 UTC, vkurennov commented on app/views/shared/_nav.html.slim
> +- if user_signed_in?
хорошо бы и на вход показывать ссылку, если юзер не залогинен

2020-09-04 13:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +RSpec.describe AnswersController, type: :controller do
а где тесты на destroy? у нас  TDD, по идее вообще не должно быть никакого кода до тех пор, пока тесты об этом не "скажут" (т.е. пока не будет падающих тестов, для прохождения которых нужно написать код). И сразу подскажу: т.к. в контроллере в destroy у тебя условие, то надо тестировать все варианты (разные контексты) - и для автора и для не-автора

2020-09-04 13:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      'тут нужен еще один тест, на связь созданного ответа и залогиненного юзера'
используй комментарии в коде для таких вещей, а не просто строки

2020-09-04 13:36 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with invalid attributes' do
а какой рендер/редирект в этом случае?

2020-09-04 13:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
замечание не исправлено, теста на связь с залогиненным юзером не вижу

2020-09-04 13:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        @question = user.questions.create(title: "MyString", body: "MyText")
зачем дублировать код? вынести эти данные в `let` или` let!`

2020-09-04 13:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        @question = user.questions.create(title: "MyString", body: "MyText")
и вновь дублирование

2020-09-04 13:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: @question.id } }.to change(Question, :count).by(0)
не `change(...).by(0)`, а `to_not change(...)`

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/browse_spec.rb
> +      expect(page).to have_content answer.body
чтобы тест был верным, надо сделать тело ответа разным в фабриках через sequence

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/create_answer_spec.rb
> +    question = create(:question, user: user)
вынеси это в given

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/create_answer_spec.rb
> +    expect(page).to have_content question.answers[0].body
тут лучше в явном виде текст проверяемый указать, так надежнее.

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/create_answer_spec.rb
> +    expect(page).to have_content 'Question can not empty!'
а причем тут Question, если создается ответ? Поэтому и надо выводить ошибки на основе данных модели, а не вручную прописывать сообщения в контроллере

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_content 'Question deleted'
надо проверить, что текста вопроса больше нет на странице

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_no_content "Delete question"
лучше `have_no_link` использовать для проверки ссылок

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    visit question_path(Question.first)
используй здесь  question, который задан через given. Зачем тут  first?

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    visit question_path(Question.first)
тут тоже используй question

2020-09-04 13:36 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +feature 'User can delete question' do
где тесты на аналогичную фичу для ответов?

2020-09-04 13:36 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где тесты на метод `author_of?` любой код, который ты пишешь должен быть покрыт тестами

2020-09-04 19:42 UTC, snblack commented on spec/features/question/delete_spec.rb
> +feature 'User can delete question' do
done

2020-09-04 20:10 UTC, snblack commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@answer.question), notice: 'Question can not empty!'
done

2020-09-04 20:13 UTC, snblack commented on app/views/questions/index.html.slim
> +      td= "#{question.title} #{question.body}"
Done

2020-09-04 20:21 UTC, snblack commented on app/views/questions/show.html.slim
> +-begin
Done

2020-09-04 20:22 UTC, snblack commented on app/views/questions/show.html.slim
> +                question_path,
Done

2020-09-04 20:24 UTC, snblack commented on app/views/questions/show.html.slim
> += form_with model: [@question, @answer], local: true do |f|
Done

2020-09-04 20:28 UTC, snblack commented on app/views/shared/_nav.html.slim
> +- if user_signed_in?
Done

2020-09-04 20:41 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +        @question = user.questions.create(title: "MyString", body: "MyText")
Done

2020-09-04 20:42 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +        @question = user.questions.create(title: "MyString", body: "MyText")
Done

2020-09-04 20:44 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: @question.id } }.to change(Question, :count).by(0)
Done

2020-09-04 21:13 UTC, snblack commented on spec/controllers/answers_controller_spec.rb
> +RSpec.describe AnswersController, type: :controller do
Done

2020-09-04 21:19 UTC, snblack commented on spec/controllers/answers_controller_spec.rb
> +    context 'with invalid attributes' do
done

2020-09-04 21:22 UTC, snblack commented on spec/features/question/browse_spec.rb
> +      expect(page).to have_content answer.body
Done

2020-09-04 21:24 UTC, snblack commented on spec/features/question/create_answer_spec.rb
> +    question = create(:question, user: user)
Done

2020-09-04 21:25 UTC, snblack commented on spec/features/question/create_answer_spec.rb
> +    expect(page).to have_content question.answers[0].body
Done

2020-09-04 21:28 UTC, snblack commented on spec/features/question/create_answer_spec.rb
> +    expect(page).to have_content 'Question can not empty!'
Done

2020-09-04 21:30 UTC, snblack commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_content 'Question deleted'
Done

2020-09-04 21:31 UTC, snblack commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_no_content "Delete question"
Done

2020-09-04 21:34 UTC, snblack commented on spec/features/question/delete_spec.rb
> +    visit question_path(Question.first)
Done

2020-09-04 21:34 UTC, snblack commented on spec/features/question/delete_spec.rb
> +    visit question_path(Question.first)
Done

2020-09-05 10:27 UTC, vkurennov approved these changes

2020-09-05 10:27 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def new
удали этот экшн, он не нужен. третий раз об этом пишу ))

2020-09-05 10:27 UTC, vkurennov commented on app/views/answers/new.html.slim
> += form_with model: [@question, @answer], local: true do |f|
экшн new не нужен, форма сразу на странице вопроса

2020-09-05 10:27 UTC, vkurennov commented on app/views/questions/show.html.slim
> +<br>
в slim не ставятся угловые скобки

2020-09-05 10:27 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'not author' do
нужен тест на рендер/редирект в этом контексте

2020-09-05 10:27 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
нужен тесты на связь с залогиненным юзером

2020-09-05 10:27 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'not author' do
какой здесь рендер/редирект?

2020-09-05 10:27 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_no_content "Delete question"
везде, где проверяешь ссылку, используй `have_link` или `have_no_link`, а не только там, где было замечание

2020-09-05 10:27 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(user.author_of?(question)).to eq true
лучше так: `expect(user).to be_author_of(question)`
работает с любыми методами-предикатами, нужно лишь вызов метода перенести после to/to_not, добавить к имени be_ и убрать знак вопроса

2020-09-06 10:15 UTC, snblack commented on app/controllers/answers_controller.rb
> +  def new
Done

2020-09-06 10:16 UTC, snblack commented on app/views/answers/new.html.slim
> += form_with model: [@question, @answer], local: true do |f|
Done

2020-09-06 10:17 UTC, snblack commented on app/views/questions/show.html.slim
> +<br>
Done

2020-09-06 10:22 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +    context 'not author' do
Done

2020-09-06 18:43 UTC, snblack commented on spec/controllers/answers_controller_spec.rb
> +    context 'not author' do
Done

2020-09-06 18:49 UTC, snblack commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_no_content "Delete question"
Done

2020-09-06 18:52 UTC, snblack commented on spec/models/user_spec.rb
> +    expect(user.author_of?(question)).to eq true
Done

2020-09-06 19:00 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
Done

2020-09-06 19:01 UTC, merged