Lesson 7 ajax
snblack/think pull request #6
Opened 2020-09-14 20:15 UTC by snblack

2020-09-15 11:42 UTC, IvanShamatov requested changes
До спек не дошел, итак пока есть с чем поработать ;)

2020-09-15 11:42 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @answer.save
Нужна обработка как позитивного сценария, так и негативного, когда сохранение не произошло и нужно показать ошибки (например, что ответ без тела ответа не сохранится)

2020-09-15 11:42 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id])
Вот этот кусочек неплохо бы вынести в before_action

2020-09-15 11:42 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @questions = Question.all
update как и create заканчиваются в большинстве случаев редиректом на какой-то другой экшн. Выбирать все вопросы здесь -- абсолютно бессмысленно, потому что они нигде не будут отрисованы

2020-09-15 11:42 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @question = @answer.question
нет никакого смысла доставать вопрос вопрос, ты его нигде не используешь в этот экшене

2020-09-15 11:42 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +  def best
экшен правильнее всего называть глаголом, а не прилагательным
например update_best, mark_as_best

2020-09-15 11:42 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    @questions =Question.all
см выше. Не понимаю в чем прикол вытаскивать все вопросы

2020-09-15 11:42 UTC, IvanShamatov commented on app/models/answer.rb
> +  default_scope {order(best: :desc)}
НИКОГДА не используй default_scope. По этому поводу можно прочитать целый доклад всяких подводных камней, а профита от него совсем немного
Скоуп сделай, но не дефолтный.

2020-09-15 11:42 UTC, IvanShamatov commented on app/models/answer.rb
> +    self.question.answers.each do |answer|
это делается в две строчки,
self.question.answers.update_all(best: false) -- и этой строкой ты обнулишь всем ответам бест, 
self.update(best: true) -- и этой строкой ты выставишь новому ответу бест.

НО, это решение в целом дурно пахнет
Смотри, у тебя по факту в таблице ответов появляется целая бесполезная колонка, которая по большей части занята False значениями.
Не лучше ли развернуть и сделать связь между вопросом и ответом, где у одного запроса есть один лучший ответ. и это будет колонка в таблице вопросов (с айдишником этого самого ответа)?

2020-09-15 11:42 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
апдейт вопросов и ответов возможен только в случае, если пользователь является автором этого самого вопроса или ответа.
Сейчас я могу сформировать curl запрос, который удалит или обновит любой вопрос или ответ

2020-09-16 16:32 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id])
Done

2020-09-16 16:35 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @question = @answer.question
Done

2020-09-16 16:37 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @questions = Question.all
Done.

2020-09-16 16:42 UTC, snblack commented on app/controllers/answers_controller.rb
> +  def best
done

2020-09-16 16:43 UTC, snblack commented on app/controllers/questions_controller.rb
> +    @questions =Question.all
Done

2020-09-16 16:48 UTC, snblack commented on app/controllers/questions_controller.rb
> +    @questions =Question.all
Если я удаляю список вопросов, то у меня падает код в js:

2020-09-16 16:48 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @answer.save
Но у меня же подгружается js.html и если ошибка то там выводиться ошибка

2020-09-16 16:48 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @questions = Question.all
Подгружается js по умолчанию и там остальная магия происходит)

2020-09-16 16:48 UTC, snblack commented on app/controllers/questions_controller.rb
> +    @questions =Question.all
![image](https://user-images.githubusercontent.com/58510471/93367778-a4dbd380-f855-11ea-9992-a3a3b6297714.png)

2020-09-16 17:01 UTC, snblack commented on app/models/answer.rb
> +  default_scope {order(best: :desc)}
done

2020-09-16 17:06 UTC, snblack commented on app/models/answer.rb
> +    self.question.answers.each do |answer|
Точно так лучше)) Я уже об этом думал. Пока оставил так, на первом своем проекте буду делать такую связь))

2020-09-16 17:15 UTC, snblack commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
Done

2020-09-17 09:12 UTC, vkurennov requested changes

2020-09-17 09:12 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      -if answer.best == TRUE
не надо сравнивать c true/false логические значения атрибутов. Если написать просто `if answer.best` будет то же самое, т.к. этот атрибут и так вернет true/false. Кроме того, в руби нет константы TRUE (точнее, она очень древняя и давно deprecated), используются литерал true/false.
Ну и для логических атрибутов в моделях, рельсы создают методы-предикаты, т.е. у тебя уже есть метод `best?`   и поэтому гораздо лучше написать так:

`if answer.best?`

2020-09-17 09:12 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answers').html ('<%= j render @question.answers %>');
по условию задания, нужно обновлять только измененный ответ, а не рендерить весь список ответов снова

2020-09-17 09:12 UTC, vkurennov commented on app/views/questions/update.js.erb
> +  $('.questions').html ('<%= j render @questions %>');
тут тоже надо обновлять только сам вопрос (ведь ты делаешь апдейто со страницы вопроса, а не со списка вопросов) и тогда в контроллере не нужно будет загружать весь список вопросов

2020-09-17 09:12 UTC, vkurennov commented on config/routes.rb
> +      get '', to: 'answers#mark_as_best', as: :best
1. get-запросы не должны изменять данные, они могут только получать, поэтому тут можно использовать только put/post/patch
2. прочиатй как добавлять к ресурсам [кастомные экшены](https://guides.rubyonrails.org/routing.html#adding-more-restful-actions)

2020-09-17 09:12 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATH #update' do
у тебя в коде условие проверки автора, значит, надо тестировать все варианты. то есть, тут должны быть контектсы для автора и для не-автора

2020-09-17 09:12 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
тут тоже должны быть контексты для автора и для не-автора

2020-09-17 09:12 UTC, vkurennov commented on spec/features/answer/choose_best_spec.rb
> +      within ".answers" do
это не доказывает, что ответ первым идет теперь в списке. надо после клика проверить значение первого элемента и убедиться, что это именно нужный ответ

2020-09-17 09:12 UTC, vkurennov commented on spec/features/answer/edit_spec.rb
> +    scenario "tries to edit other user's question", js: true do
похожий сценарий нужен для незалогиненного юзера

2020-09-17 09:12 UTC, vkurennov commented on spec/features/question/edit_spec.rb
> +    scenario "tries to edit other user's question", js: true do
нужен похожий сценарий для незалогиненного юзера. тут, кстати, `js: true` не обязателен, т.к. реального взаимодействия не происходит

2020-09-17 09:12 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  it 'best answer' do
это не верный тест. ты проверяешь возвращаемое значение метода, а надо проверить что а) у ответа, у которого вызван метод, нужный атрибут установлен в нужное значение, б) если уже был лучший ответ, а метод вызван у другого ответа для этого же вопроса, то он перестает быть лучшим и в) что вызов метода у ответов для разных вопросов не влияет друг на друга (это три разных теста)

2020-09-17 09:12 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    expect(answer.choose_best).to eq TRUE
я не знаю откуда ты откопал константу TRUE, но забудь про нее навсегда. Есть только true и false

2020-09-17 10:22 UTC, snblack commented on app/controllers/answers_controller.rb
> +    if current_user = @answer.user
1. Done

2020-09-17 10:24 UTC, snblack commented on app/controllers/answers_controller.rb
> +    if current_user = @answer.user
2. Done

2020-09-17 13:13 UTC, snblack commented on app/controllers/answers_controller.rb
> +      respond_to do |format|
Done

2020-09-17 13:14 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @answer.choose_best
Done

2020-09-17 13:21 UTC, snblack commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Done

2020-09-17 13:44 UTC, snblack commented on config/routes.rb
> +      get '', to: 'answers#mark_as_best', as: :best
Done

2020-09-17 13:54 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:answer_id])
Done

2020-09-17 15:48 UTC, snblack commented on app/controllers/questions_controller.rb
> +      @questions = Question.all
Done

2020-09-17 16:19 UTC, snblack commented on app/models/answer.rb
> +  def choose_best
DONE

2020-09-17 16:24 UTC, snblack commented on app/views/answers/_answer.html.slim
> +      -if answer.best == TRUE
DONE

2020-09-17 16:26 UTC, snblack commented on app/views/questions/update.js.erb
> +  $('.questions').html ('<%= j render @questions %>');
done

2020-09-17 16:33 UTC, snblack commented on app/views/answers/update.js.erb
> +  $('.answers').html ('<%= j render @question.answers %>');
Done

2020-09-17 16:45 UTC, snblack commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATH #update' do
Done

2020-09-17 16:50 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
Done

2020-09-17 16:57 UTC, snblack commented on spec/features/answer/choose_best_spec.rb
> +      within ".answers" do
done

2020-09-17 17:03 UTC, snblack commented on spec/features/answer/edit_spec.rb
> +    scenario "tries to edit other user's question", js: true do
done

2020-09-17 17:13 UTC, snblack commented on spec/features/question/edit_spec.rb
> +    scenario "tries to edit other user's question", js: true do
done

2020-09-17 17:30 UTC, snblack commented on spec/models/answer_spec.rb
> +  it 'best answer' do
done

2020-09-17 17:31 UTC, snblack commented on spec/models/answer_spec.rb
> +    expect(answer.choose_best).to eq TRUE
Done ЗАбыл)

2020-09-18 11:23 UTC, vkurennov approved these changes

2020-09-18 11:23 UTC, vkurennov commented on app/models/answer.rb
> +      self.question.answers.update_all(best: false)
self здесь и в след. строке необязателен

2020-09-18 11:23 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    expect(answer.best).to eq false
лучше исмпользовать конструкции вида `expect(answer).to be_best`

2020-09-18 11:30 UTC, snblack commented on app/models/answer.rb
> +      self.question.answers.update_all(best: false)
Done

2020-09-18 11:30 UTC, snblack commented on spec/models/answer_spec.rb
> +    expect(answer.best).to eq false
done

2020-09-18 11:31 UTC, merged