Lesson 9 forms and assoc
snblack/think pull request #8
Opened 2020-10-06 00:19 UTC by snblack

2020-10-06 09:12 UTC, IvanShamatov requested changes
Не все отстмотрел, но то, что отсмотрел требует переработки

2020-10-06 09:12 UTC, IvanShamatov commented on app/models/link.rb
> +  end
надо использовать URI.parse для вытаскивания
и ERB::Util#html_escape

Смотри, возможно ты еще не вкурсе и не сталкивался с различного вида уязвимостями, но тут у тебя есть возможность заинжектить джаваскрипт. https://owasp.org/www-community/xss-filter-evasion-cheatsheet
Ведь для того чтобы ты пропустил ссылку, достаточно в любом месте воткнуть gist.github.com/1/1 и все.

2020-10-06 09:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      Answer.transaction do
кроме того, этому вообще не место в контроллере, нужно награждение перенести в сам метод choose_best модели, чтобы это происходило вне зависимости от того, когда этот метод вызывается

2020-10-06 14:31 UTC, snblack commented on app/controllers/answers_controller.rb
> +      Answer.transaction do
+ сделал

2020-10-06 14:32 UTC, snblack commented on app/models/answer.rb
> +  has_one :reward, as: :rewardable
Done

2020-10-06 14:39 UTC, snblack commented on app/models/question.rb
> +  has_one :reward, dependent: :delete, as: :rewardable
Done

2020-10-06 15:12 UTC, snblack commented on app/models/reward.rb
> +  belongs_to :rewardable, polymorphic: true
Done

2020-10-06 15:15 UTC, snblack commented on app/views/answers/_answer.html.slim
> +      p= link_to 'Choose answer', mark_as_best_answer_path(answer), method: :put, class: 'best-answer-link hidden', data: { answer_id: answer.id }, remote: true
done

2020-10-07 06:48 UTC, IvanShamatov requested changes
1. Реализовать следующие истории:
- [x] Пользователь может добавлять несколько ссылок к вопросу или ответу. Для реализации можно использовать gem cocoon.
- [x] При добавлении ссылки валидировать ее на формат URL, если ссылка не валидная, не создавать объект и выводить сообщение об ошибке валидации
- [x] Если дана ссылка на gist, то выводить сразу gist, а не просто ссылку.
- [x] Автор может удалить ссылки у своего вопроса/ответа
- [x] При редактировании  вопроса/ответа автор может добавить новые ссылки 


2. Реализовать награждение за лучший ответ:
- [x] При создании вопроса, пользователь может также создать награду за лучший ответ, которую получит отвечающий
- [x] Когда автор вопроса выбирает лучший ответ, пользователь, давший лучший ответ получает назначенную награду
- [x] Пользователь может просматривать полученные им награды
- [x] При этом он видит заголовок вопроса, изображение награды и ее название

Нет спеки на обновленное поведение choose_best в модели Answre

Ты задание сделал, это правда, но все еще нужно доработать. Если сделаешь в течении дня, напиши в слак, чтоб я оперативно принял.

2020-10-07 06:48 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @reward = @answer.question.reward
эта строка становится бесполезной

2020-10-07 06:48 UTC, IvanShamatov commented on app/models/answer.rb
> +      self.user.rewards << self.question.reward
должно работать и без `self.`, но это не критично

2020-10-07 06:48 UTC, IvanShamatov commented on app/views/answers/_answer.html.slim
> +          li= link_to link.name, link.url
тут тоже все таки стоит валидировать инпут. Ты ведь не фильтранул ссылку, если она не содержит gist,
Может давай сделаем валидацию на это поле? или html_safe применим к урлу?

2020-10-07 06:48 UTC, IvanShamatov commented on app/views/answers/_answer.html.slim
> +          li= link_to link.name, link.url
https://coderwall.com/p/ztig5g/validate-urls-in-rails

2020-10-07 06:48 UTC, IvanShamatov commented on app/views/questions/_question_show.html.slim
> +    - @question.links.each do |link|
выглядит как очень похожий кусок с паршлом ответов, может вытащим одинаковую логику, и будем передавать либо @question, либо answer?
Если не ошибаюсь, верстка не отличается

2020-10-07 06:48 UTC, IvanShamatov commented on app/views/questions/_question_show.html.slim
> +  p Links:
тоже похожий кусок.

2020-10-07 06:48 UTC, IvanShamatov commented on spec/controllers/links_controller_spec.rb
> +
destroy надо протестить.

2020-10-07 06:48 UTC, IvanShamatov commented on spec/controllers/questions_controller_spec.rb
> +    it 'assigns a new Question to @question' do
описание не пофиксил после копипасты

2020-10-07 06:48 UTC, IvanShamatov commented on spec/controllers/rewards_controller_spec.rb
> +
index надо протестить

2020-10-07 06:48 UTC, IvanShamatov commented on spec/features/answer/add_links_spec.rb
> +
пробельнулся не на той строке (придираюсь)

2020-10-07 06:48 UTC, IvanShamatov commented on app/controllers/rewards_controller.rb
> +    @rewards = current_user.rewards
у тебя тут N+1 при рендеринге

2020-10-07 13:21 UTC, snblack commented on app/controllers/answers_controller.rb
> +    @reward = @answer.question.reward
Done

2020-10-07 13:21 UTC, snblack commented on app/models/answer.rb
> +      self.user.rewards << self.question.reward
Done

2020-10-07 13:30 UTC, snblack commented on app/views/answers/_answer.html.slim
> +          li= link_to link.name, link.url
done

2020-10-07 13:43 UTC, snblack commented on app/views/questions/_question_show.html.slim
> +    - @question.links.each do |link|
Done

2020-10-07 15:10 UTC, snblack commented on spec/controllers/links_controller_spec.rb
> +
Done

2020-10-07 15:11 UTC, snblack commented on spec/controllers/questions_controller_spec.rb
> +    it 'assigns a new Question to @question' do
Done

2020-10-07 15:35 UTC, snblack commented on spec/controllers/rewards_controller_spec.rb
> +
Done

2020-10-07 15:57 UTC, snblack commented on app/controllers/rewards_controller.rb
> +    @rewards = current_user.rewards
Done

2020-10-07 16:32 UTC, IvanShamatov commented on app/controllers/rewards_controller.rb
> +    @rewards = Reward.includes(:user).where("user_id = ?", current_user)
Reward.where(user: current_user).includes(:questions)?

2020-10-07 16:32 UTC, IvanShamatov approved these changes

2020-10-07 17:19 UTC, merged