v8
snblack/think pull request #9
Opened 2020-10-09 14:45 UTC by snblack

2020-10-10 18:15 UTC, IvanShamatov requested changes

2020-10-10 18:15 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +
Так, совсем мне не нравится такой код. Его нужно отрефакторить.
Во-первых, ты здесь так или иначе везде возвращаешь JSON, поэтому respond_to и format.json мы просто на просто убираем.

Остается
```ruby
  def errors_user
    @answer.errors.add(:user, :invalid, message: "You can not vote for self answer")
    render json: @answer.errors.full_messages, status: :unprocessable_entity
  end

  def create_vote(value_vote)
    @answer.votes.create(user: current_user, value: value_vote)

    update_answer.votes.sum(:value)(@answer)
  end

  def respond_create
    if @answer.save
      render json: @answer
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  def cancel_vote
    @answer.votes.find_by(user: current_user).destroy

    update_rating(@answer)
    if @answer.save
      render json: @answer
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  def errors_vote
    @answer.errors.add(:rating, :invalid, message: "You voted early")
    render json: @answer.errors.full_messages, status: :unprocessable_entity
  end
```


Во-вторых, у тебя получается много повторяющихся частей в этих самых методах. Код добавился, а не уменьшился с момента, когда ты вынес этот код в методы
Сейчас мы сделаем обратное преобразование, т.е. все вызовы методов заменим на тот код. который внутри.

```ruby

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_answer, only: %i[update destroy mark_as_best up down]

  def up
    if current_user.author_of?(@answer)
      @answer.errors.add(:user, :invalid, message: "You can not vote for self answer")
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    else
      if @answer.votes.exists?
        if @answer.votes[0].value == 1
          @answer.errors.add(:rating, :invalid, message: "You voted early")
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        elsif @answer.votes[0].value == -1
          @answer.votes.find_by(user: current_user).destroy
          rating = answer.votes.sum(:value)
          @answer.rating = rating
          if @answer.save
            render json: @answer
          else
            render json: @answer.errors.full_messages, status: :unprocessable_entity
          end
        end
      else
        @answer.votes.create(user: current_user, value: 1)
        rating = answer.votes.sum(:value)
        @answer.rating = rating
        if @answer.save
          render json: @answer
        else
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  def down
    if current_user.author_of?(@answer)
      @answer.errors.add(:user, :invalid, message: "You can not vote for self answer")
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    else
      if @answer.votes.exists?
        if @answer.votes[0].value == 1
          @answer.votes.find_by(user: current_user).destroy
          rating = answer.votes.sum(:value)
          @answer.rating = rating
          if @answer.save
            render json: @answer
          else
            render json: @answer.errors.full_messages, status: :unprocessable_entity
          end
        elsif @answer.votes[0].value == -1
          @answer.errors.add(:rating, :invalid, message: "You voted early")
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      else
        @answer.votes.create(user: current_user, value: -1)
        rating = answer.votes.sum(:value)
        @answer.rating = rating
        if @answer.save
          render json: @answer
        else
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  private


  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end
end

```

После такого обратного преобразования, мы видим, как разрослись up и down, но у них повторяется много всего, связанного с рендерингом ошибок
Эти части не зависят от if и else

```ruby
  def up
    if current_user.author_of?(@answer)
      @answer.errors.add(:user, :invalid, message: "You can not vote for self answer")
    else
      if @answer.votes.exists?
        if @answer.votes[0].value == 1
          @answer.errors.add(:rating, :invalid, message: "You voted early")
        elsif @answer.votes[0].value == -1
          @answer.votes.find_by(user: current_user).destroy
        end
      else
        @answer.votes.create(user: current_user, value: 1)
      end
    end
    @answer.rating = @answer.votes.sum(:value)
    if @answer.save
      render json: @answer
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end  
  end
```

Вот таким небольшим у нас становится сам метод на up, down (будут практически идентичны, просто с разным порядком ифов).
Но давай изменять дальше. Сохранять рейтинг в модели ответа - в целом идея здравая, но вовсе не обязательная. Оставим.


Давай разбираться с логикой. Почему, если мы хотим проголосовать, при попытке проголосовать, мы добавляем ошибку к ответу? 
С тем же успехом мы могли бы рендерить текст используя render json: {error: :unauthorized}. Уже на первом же этапе мы можем отсечь целую ветку if/else

```ruby
  def up
    return anauthorized! if current_user.author_of?(@answer)
    if @answer.votes.exists?
      if @answer.votes[0].value == 1
        @answer.errors.add(:rating, :invalid, message: "You voted early")
      elsif @answer.votes[0].value == -1
        @answer.votes.find_by(user: current_user).destroy
      end
    else
      @answer.votes.create(user: current_user, value: 1)
    end

    @answer.rating = @answer.votes.sum(:value)
    if @answer.save
      render json: @answer
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end  
  end

  def anauthorized!
    render json: { error: :unauthorized }
  end
```

Так ли нам нужно обязательно скзаать пользователю, что он уже голосовал? Мы вообще можем не показывать ссылку пользователю на голосование вверх, если он уже голосовал вверх еще в момент рендеринга страницы.
И тут так получается: Если голосовал вниз, то нам нужно переголосовать вверх. Если не голосовал, то тоже нужно проголосовать вверх. И тогда условие, существует ли голос, или не существует в базе -- нам абсолютно не важно

```ruby
  def up
    return anauthorized! if current_user.author_of?(@answer)
    
    @answer.votes.find_by(user: current_user).destroy
    @answer.votes.create(user: current_user, value: 1)
    @answer.update(rating: @answer.votes.sum(:value))
    render json: { answer_id: @answer.id, rating: @answer.rating }
  end

  def anauthorized!
    render json: { error: :unauthorized }
  end
```

И последний шаг up, down отличаются только одной цифрой

```ruby
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_answer, only: %i[update destroy mark_as_best up down]

  def up
    vote(1)
  end

  def down
    vote(-1)
  end

  def vote(value)
    return anauthorized! if current_user.author_of?(@answer)
    
    @answer.votes.find_by(user: current_user).destroy
    @answer.votes.create(user: current_user, value: value)
    @answer.update(rating: @answer.votes.sum(:value))
    render json: { answer_id: @answer.id, rating: @answer.rating }
  end

  private


  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end
end

```
Согласно зданию тебе нужно использовать Concerns, чтобы вытащить повторяющуюся логику в модуль (например, Rateable), а логика у тебя для голосования в вопросе и ответ будет абсолютно одинаковой. [...]

2020-10-12 09:01 UTC, IvanShamatov requested changes

2020-10-12 09:01 UTC, IvanShamatov commented on spec/controllers/questions_controller_spec.rb
> +  # describe 'PUT #up' do
Контроллер спеки не сделал. 
для таких штук как раз и существуют shared examples, 
https://relishapp.com/rspec/rspec-core/v/3-9/docs/example-groups/shared-examples

2020-10-12 09:14 UTC, snblack commented on app/models/answer.rb
> +  validates :body, :rating, presence: true
done

2020-10-12 09:14 UTC, snblack commented on app/models/question.rb
> +  validates :title, :body, :rating, presence: true
done

2020-10-12 09:17 UTC, snblack commented on app/views/questions/_question_show.html.slim
> +  p[class='vote_question_up id-#{question.id} hidden']= link_to 'Up', up_question_path(question), method: :put, remote: true
done

2020-10-12 14:23 UTC, snblack commented on config/routes.rb
> +    member do
Done

2020-10-12 14:30 UTC, snblack commented on spec/features/vote/vote_for_answer_spec.rb
> +feature 'user can vote for question/answer' do
DOne

2020-10-12 14:31 UTC, snblack commented on spec/features/vote/vote_for_question_spec.rb
> +feature 'user can vote for question/answer' do
Done

2020-10-12 19:11 UTC, IvanShamatov approved these changes

2020-10-12 19:11 UTC, IvanShamatov commented on spec/controllers/concerns/answer_controller.rb
> +end
Не понимаю, куда ты торопишься и спешишь. Вот в чем смысл shared_examples
```ruby
RSpec.shared_examples 'votable answer' do |model|
  let(:user) { create(:user) }
  let(:resource) { create(model, user: user) }

  describe 'PUT #up' do
    before { login(user) }

    context 'Not author' do
      it 'saves a new vote in the database' do
        expect { put :up, params: { model => resource.id} }.to change(Vote, :count).by(1)
      end
    end

    context 'Author' do
      it 'does not save the resource' do
        expect { put :up, params: { model => resource.id, user: user} }.to_not change(Vote, :count)
      end
    end
  end
end

RSpec.describe AnswersController, type: :controller do
  it_behaves_like "votable answer", :answer
end

RSpec.describe QuestionsController, type: :controller do
  it_behaves_like "votable question", :question
end
```

2020-10-12 19:11 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +    @votable.update(rating: @votable.votes.sum(:value))
я нашел еще более элегантное (как мне кажется) решение:
```ruby
@votable.votes.find_or_initialize_by(user: current_user) { |v| v.update(value: value) }
```
тогда дестрой не будет осуществляться, только обновление значения, если таковое было, и не будет вообще ничего делаться, если значение не изменилось.

2020-10-13 15:58 UTC, snblack commented on app/views/questions/_question_show.html.slim
> +question.votes.find_by(user: current_user)&.value == -1
Done

2020-10-13 16:00 UTC, snblack commented on spec/controllers/concerns/answer_controller.rb
> +end
Done

2020-10-13 16:07 UTC, merged